/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 12-bře-2024 20:16:34 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Adresa` CASCADE
;

DROP TABLE IF EXISTS `Album` CASCADE
;

DROP TABLE IF EXISTS `Au_a` CASCADE
;

DROP TABLE IF EXISTS `Beznyuzivatel` CASCADE
;

DROP TABLE IF EXISTS `beznyUzivatelPlaylist` CASCADE
;

DROP TABLE IF EXISTS `Kapela` CASCADE
;

DROP TABLE IF EXISTS `KapelaAu_a` CASCADE
;

DROP TABLE IF EXISTS `Playlist` CASCADE
;

DROP TABLE IF EXISTS `PlaylistSkladba` CASCADE
;

DROP TABLE IF EXISTS `Recenze` CASCADE
;

DROP TABLE IF EXISTS `Skladba` CASCADE
;

DROP TABLE IF EXISTS `SkladbaZanr` CASCADE
;

DROP TABLE IF EXISTS `Umelec` CASCADE
;

DROP TABLE IF EXISTS `UmelecAlbum` CASCADE
;

DROP TABLE IF EXISTS `UmelecAu_a` CASCADE
;

DROP TABLE IF EXISTS `Uzivatel` CASCADE
;

DROP TABLE IF EXISTS `Zanr` CASCADE
;

/* Create Tables */

CREATE TABLE `Adresa`
(
	`Cislopopisne` varchar(20) NOT NULL,
	`Mesto` varchar(85) NOT NULL,
	`Psc` varchar(10) NOT NULL,
	`Ulice` varchar(50) NULL,
	`AdresaID` INT NOT NULL AUTO_INCREMENT,
	CONSTRAINT `PK_Adresa` PRIMARY KEY (`AdresaID` ASC)
)

;

CREATE TABLE `Album`
(
	`Delka` TIME NOT NULL,
	`Nazev` varchar(50) NOT NULL,
	`Pocetskladeb` INT NOT NULL,
	`Popis` TEXT NULL,
	`Publikovano` BOOL NOT NULL,
	`AlbumID` INT NOT NULL AUTO_INCREMENT,
	`CoverImage` VARCHAR(255) NULL,
	CONSTRAINT `PK_Album` PRIMARY KEY (`AlbumID` ASC)
)

;

CREATE TABLE `Au_a`
(
	`Copyright` varchar(400) NOT NULL,
	`Au_aID` INT NOT NULL AUTO_INCREMENT,
	`AlbumID` INT NOT NULL,
	CONSTRAINT `PK_Au_a` PRIMARY KEY (`Au_aID` ASC)
)

;

CREATE TABLE `Beznyuzivatel`
(
	`Jmeno` VARCHAR(25) NOT NULL,
	`Oblibenezanry` INT NULL,
	`Prijmeni` varchar(25) NULL,
	`BeznyuzivatelID` INT NOT NULL AUTO_INCREMENT,
	CONSTRAINT `PK_Beznyuzivatel` PRIMARY KEY (`BeznyuzivatelID` ASC)
)

;

CREATE TABLE `beznyUzivatelPlaylist`
(
	`PlaylistID` INT NOT NULL,
	`BeznyuzivatelID` INT NOT NULL
)

;

CREATE TABLE `Kapela`
(
	`Clenovekapely` INT NOT NULL,
	`Jmeno` varchar(50) NOT NULL,
	`Popis` TEXT NULL,
	`KapelaID` INT ZEROFILL NOT NULL AUTO_INCREMENT,
	CONSTRAINT `PK_Kapela` PRIMARY KEY (`KapelaID` ASC)
)

;

CREATE TABLE `KapelaAu_a`
(
	`Au_aID` INT NOT NULL AUTO_INCREMENT,
	`KapelaID` INT NOT NULL
)

;

CREATE TABLE `Playlist`
(
	`Coverimage` varchar(255) NULL,
	`Datumvzniku` DATE NOT NULL,
	`Delka` TIME NOT NULL,
	`Nazev` varchar(50) NOT NULL,
	`Pocetskladeb` INT NOT NULL,
	`Popis` varchar(0) NULL,
	`Tvurce` varchar(255) NOT NULL,
	`PlaylistID` INT NOT NULL AUTO_INCREMENT,
	CONSTRAINT `PK_Playlist` PRIMARY KEY (`PlaylistID` ASC)
)

;

CREATE TABLE `PlaylistSkladba`
(
	`SkladbaID` INT NOT NULL,
	`PlaylistID` INT NOT NULL
)

;

CREATE TABLE `Recenze`
(
	`Komentar` TEXT NULL,
	`Nadpis` varchar(50) NOT NULL,
	`Pocethvezd` INT NOT NULL,
	`RecenzeID` INT NOT NULL AUTO_INCREMENT,
	`AlbumID` INT NOT NULL,
	`BeznyuzivatelID` INT NOT NULL,
	`KapelaID` INT NOT NULL,
	`UmelecID` INT NOT NULL,
	`SkladbaID` INT NOT NULL,
	CONSTRAINT `PK_Recenze` PRIMARY KEY (`RecenzeID` ASC)
)

;

CREATE TABLE `Skladba`
(
	`Audioslozka` varchar(255) NOT NULL,
	`Coverimage` varchar(255) NOT NULL,
	`Delka` TIME NOT NULL,
	`Jmeno` varchar(50) NOT NULL,
	`Pocetprehrani` INT NOT NULL,
	`SkladbaID` INT NOT NULL AUTO_INCREMENT,
	`AlbumID` INT NOT NULL,
	CONSTRAINT `PK_Skladba` PRIMARY KEY (`SkladbaID` ASC)
)

;

CREATE TABLE `SkladbaZanr`
(
	`ZanrID` INT NOT NULL,
	`SkladbaID` INT NOT NULL
)

;

CREATE TABLE `Umelec`
(
	`Jmeno` varchar(50) NOT NULL,
	`Popis` TEXT NULL,
	`UmelecID` INT NOT NULL AUTO_INCREMENT,
	CONSTRAINT `PK_Umelec` PRIMARY KEY (`UmelecID` ASC)
)

;

CREATE TABLE `UmelecAlbum`
(
	`AlbumID` INT NOT NULL,
	`UmelecID` INT NOT NULL
)

;

CREATE TABLE `UmelecAu_a`
(
	`Au_aID` INT NULL,
	`UmelecID` INT NULL
)

;

CREATE TABLE `Uzivatel`
(
	`Datumnarozeni` DATE NOT NULL,
	`Datumzalozeni` DATE NOT NULL,
	`Email` VARCHAR(100) NOT NULL,
	`Platnost` BOOL NOT NULL,
	`Profilovyobrazek` varchar(255) NOT NULL,
	`UzivatelID` INT NOT NULL AUTO_INCREMENT,
	`AdresaID` INT NOT NULL,
	`BeznyuzivatelID` INT NULL,
	`KapelaID` INT NULL,
	`UmelecID` INT NULL,
	CONSTRAINT `PK_Uzivatel` PRIMARY KEY (`UzivatelID` ASC)
)

;

CREATE TABLE `Zanr`
(
	`Anotace` varchar(100) NOT NULL,
	`Nazev` varchar(25) NOT NULL,
	`ZanrID` INT NOT NULL AUTO_INCREMENT,
	CONSTRAINT `PK_Zanr` PRIMARY KEY (`ZanrID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Au_a` 
 ADD CONSTRAINT `FK_Au_a_Album`
	FOREIGN KEY (`AlbumID`) REFERENCES `Album` (`AlbumID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `beznyUzivatelPlaylist` 
 ADD CONSTRAINT `FK_beznyUzivatelPlaylist_Playlist`
	FOREIGN KEY (`PlaylistID`) REFERENCES `Playlist` (`PlaylistID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `beznyUzivatelPlaylist` 
 ADD CONSTRAINT `FK_beznyUzivatelPlaylist_beznyUzivatel`
	FOREIGN KEY (`BeznyuzivatelID`) REFERENCES `Beznyuzivatel` (`BeznyuzivatelID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `KapelaAu_a` 
 ADD CONSTRAINT `FK_KapelaAu_a_Au_a`
	FOREIGN KEY (`Au_aID`) REFERENCES `Au_a` (`Au_aID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `KapelaAu_a` 
 ADD CONSTRAINT `FK_KapelaAu_a_Kapela`
	FOREIGN KEY (`KapelaID`) REFERENCES `Kapela` (`KapelaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `PlaylistSkladba` 
 ADD CONSTRAINT `FK_PlaylistSkladba_Skladba`
	FOREIGN KEY (`SkladbaID`) REFERENCES `Skladba` (`SkladbaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `PlaylistSkladba` 
 ADD CONSTRAINT `FK_PlaylistSkladba_Playlist`
	FOREIGN KEY (`PlaylistID`) REFERENCES `Playlist` (`PlaylistID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Recenze` 
 ADD CONSTRAINT `FK_Recenze_Album`
	FOREIGN KEY (`AlbumID`) REFERENCES `Album` (`AlbumID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Recenze` 
 ADD CONSTRAINT `FK_Recenze_Beznyuzivatel`
	FOREIGN KEY (`BeznyuzivatelID`) REFERENCES `Beznyuzivatel` (`BeznyuzivatelID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Recenze` 
 ADD CONSTRAINT `FK_Recenze_Kapela`
	FOREIGN KEY (`KapelaID`) REFERENCES `Kapela` (`KapelaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Recenze` 
 ADD CONSTRAINT `FK_Recenze_Umelec`
	FOREIGN KEY (`UmelecID`) REFERENCES `Umelec` (`UmelecID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Recenze` 
 ADD CONSTRAINT `FK_Recenze_Skladba`
	FOREIGN KEY (`SkladbaID`) REFERENCES `Skladba` (`SkladbaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Skladba` 
 ADD CONSTRAINT `FK_Skladba_Album`
	FOREIGN KEY (`AlbumID`) REFERENCES `Album` (`AlbumID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `SkladbaZanr` 
 ADD CONSTRAINT `FK_SkladbaZanr_Zanr`
	FOREIGN KEY (`ZanrID`) REFERENCES `Zanr` (`ZanrID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `SkladbaZanr` 
 ADD CONSTRAINT `FK_SkladbaZanr_Skladba`
	FOREIGN KEY (`SkladbaID`) REFERENCES `Skladba` (`SkladbaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `UmelecAlbum` 
 ADD CONSTRAINT `FK_UmelecAlbum_Album`
	FOREIGN KEY (`AlbumID`) REFERENCES `Album` (`AlbumID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `UmelecAlbum` 
 ADD CONSTRAINT `FK_UmelecAlbum_Umelec`
	FOREIGN KEY (`UmelecID`) REFERENCES `Umelec` (`UmelecID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `UmelecAu_a` 
 ADD CONSTRAINT `FK_UmelecAu_a_Au_a`
	FOREIGN KEY (`Au_aID`) REFERENCES `Au_a` (`Au_aID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `UmelecAu_a` 
 ADD CONSTRAINT `FK_UmelecAu_a_Umelec`
	FOREIGN KEY (`UmelecID`) REFERENCES `Umelec` (`UmelecID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Uzivatel` 
 ADD CONSTRAINT `FK_Uzivatel_Adresa`
	FOREIGN KEY (`AdresaID`) REFERENCES `Adresa` (`AdresaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Uzivatel` 
 ADD CONSTRAINT `FK_Uzivatel_Beznyuzivatel`
	FOREIGN KEY (`BeznyuzivatelID`) REFERENCES `Beznyuzivatel` (`BeznyuzivatelID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Uzivatel` 
 ADD CONSTRAINT `FK_Uzivatel_Kapela`
	FOREIGN KEY (`KapelaID`) REFERENCES `Kapela` (`KapelaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Uzivatel` 
 ADD CONSTRAINT `FK_Uzivatel_Umelec`
	FOREIGN KEY (`UmelecID`) REFERENCES `Umelec` (`UmelecID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 
